2024-08-03 09:44 ERROR Traceback (most recent call last):
  File "c:\Users\Wour\Desktop\Program\RL_trading\finrl_achieve\project\TradingSysteam.py", line 279, in main
    balance_balance_map = self.check_money_level()
  File "c:\Users\Wour\Desktop\Program\RL_trading\finrl_achieve\project\TradingSysteam.py", line 207, in check_money_level
    return self.dataprovider.Binanceapp.get_alluser_futuresaccountbalance()
  File "c:\Users\Wour\Desktop\Program\RL_trading\finrl_achieve\project\Major\custom.py", line 65, in wrapper
    result = func(self, client, *args, **kwargs)
  File "c:\Users\Wour\Desktop\Program\RL_trading\finrl_achieve\project\Major\custom.py", line 648, in get_alluser_futuresaccountbalance
    for i in client.futures_account_balance():
  File "C:\Users\Wour\Desktop\Program\RL_trading\lib\site-packages\binance\client.py", line 6574, in futures_account_balance
    return self._request_futures_api('get', 'balance', True, 2, data=params)
  File "C:\Users\Wour\Desktop\Program\RL_trading\lib\site-packages\binance\client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "C:\Users\Wour\Desktop\Program\RL_trading\lib\site-packages\binance\client.py", line 359, in _request
    return self._handle_response(self.response)
  File "C:\Users\Wour\Desktop\Program\RL_trading\lib\site-packages\binance\client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-2015): Invalid API-key, IP, or permissions for action, request ip: 118.171.214.150

2024-08-03 09:48 ERROR Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000140901E3D00>
